### ISSUE TITLE
Android samples not working

### ISSUE THREAD

**Issue by dqtdev** [inka-pallycon/pallycon-widevine-android-sdk#2]
I downloaded "simple" sample project and run it and got this exception, the "advanced" sample is not working too. Please check the samples if there are any problems.

```
Playback error
  com.google.android.exoplayer2.ExoPlaybackException: Source error
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:586)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loopOnce(Looper.java:226)
      at android.os.Looper.loop(Looper.java:313)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
      at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:544)
      at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionError(DefaultDrmSession.java:247)
      at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$ProvisioningManagerImpl.onProvisionError(DefaultDrmSessionManager.java:898)
      at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionResponse(DefaultDrmSession.java:401)
      at com.google.android.exoplayer2.drm.DefaultDrmSession.access$000(DefaultDrmSession.java:61)
      at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:581)
      at android.os.Handler.dispatchMessage(Handler.java:106)
      at android.os.Looper.loopOnce(Looper.java:226) 
      at android.os.Looper.loop(Looper.java:313) 
      at android.os.HandlerThread.run(HandlerThread.java:67) 
  Caused by: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
      at d.c.a(SourceFile:55)
      at d.c.executeProvisionRequest(SourceFile:7)
      at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:620)
      at android.os.Handler.dispatchMessage(Handler.java:106) 
      at android.os.Looper.loopOnce(Looper.java:226) 
      at android.os.Looper.loop(Looper.java:313) 
      at android.os.HandlerThread.run(HandlerThread.java:67) 
  Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
      at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:329)
      at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
      at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
      at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:79)
      at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:73)
      at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:183)
      at d.c.a(SourceFile:30)
      at d.c.executeProvisionRequest(SourceFile:7) 
      at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:620) 
      at android.os.Handler.dispatchMessage(Handler.java:106) 
      at android.os.Looper.loopOnce(Looper.java:226) 
      at android.os.Looper.loop(Looper.java:313) 
      at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by Inkayuyu04** [comment]
`val config = PallyConDrmConfigration(
            siteId = "",
            customData = "",
            httpHeaders = null,
            drmLicenseUrl = "https://license-global.pallycon.com/ri/licenseManager.do")`
            
If you specified the drmLicenseUrl value as shown in the code above, please check the url value. Based on the error content, it seems that the server you connected to get the license is generating an http error, 404. 404 is an error that the URL does not exist.
